### ISSUE TITLE
No module named 'sasl_compat'

### ISSUE THREAD

**Issue by carlsunderman** [devinstevenson/pure-transport#1]
i get this error with both the hive connection and sql alchemy connection example

C:\<Python path>\bin\Python\envs\hive\lib\site-packages\puretransport\factory.py in transport_factory(host, port, username, password, **kwargs)
     else:
--->         from sasl_compat import PureSASLClient
                def sasl_factory():

ModuleNotFoundError: No module named 'sasl_compat'

**Comment by chenrulongmaster** [comment]
same issue

**Comment by jagimene** [comment]
same issue here

**Comment by devinstevenson** [comment]
I'll take a look at this tonight. @chenrulongmaster @jagimene Are you Windows users too?

**Comment by jagimene** [comment]
Yes, windows 10 x64

**Comment by jagimene** [comment]
Yes, windows 10 x64

**Comment by devinstevenson** [comment]
I tested this on a windows machine from doing a pip install and it worked fine. Did you do pip install?

I had some typos in the example file that are now fixed. Not sure if that was the issue.

**Comment by jagimene** [comment]
Yes, I noticed the typos and fixed while testing.
But no luck, I have the same error

**Comment by devinstevenson** [comment]
Can you list the contents of your site-packages/puretransport folder? Also try to reinstall
`pip install pure-transport --upgrade`

**Comment by devinstevenson** [comment]
this is now fixed with version 0.1.3
`pip install pure-transport --upgrade`

**Comment by jagimene** [comment]
Hi, 
I did de upgrade.

Now, when I try to connect i get this error

transport = puretransport.transport_factory(host=host,
                                            port=port,
                                            username=username,
                                            password=password)

hive_con = hive.connect(username=username, thrift_transport=transport, database='default')
Traceback (most recent call last):

  File "<ipython-input-5-2d69d67bb176>", line 6, in <module>
    hive_con = hive.connect(username=username, thrift_transport=transport, database='default')

  File "C:\Continuum\anaconda3\lib\site-packages\pyhive\hive.py", line 94, in connect
    return Connection(*args, **kwargs)

  File "C:\Continuum\anaconda3\lib\site-packages\pyhive\hive.py", line 192, in __init__
    self._transport.open()

  File "C:\Continuum\anaconda3\lib\site-packages\thrift_sasl\__init__.py", line 82, in open
    self._send_message(self.START, chosen_mech)

  File "C:\Continuum\anaconda3\lib\site-packages\thrift_sasl\__init__.py", line 101, in _send_message
    self._trans.write(header + body)

TypeError: can't concat str to bytes

Any ideas?

**Comment by devinstevenson** [comment]
This is an issue with thrift_sasl on python3. https://github.com/cloudera/thrift_sasl/issues/14
I'll look into it.

**Comment by phumne** [comment]
Hi @devinstevenson ,

Any luck with issue on thrift_sasl on python3?

**Comment by Stalker404** [comment]
If anyone recived TypeError: can't concat str to bytes:
Temporary solution is edit thrift_sasl/__init__.py 
You need add 2 **strings** to encode body to bytes.
  def _send_message(self, status, body):
    header = struct.pack(">BI", status, len(body))
    **if isinstance(body, str):
      body = body.encode()**
    self._trans.write(header + body)
    self._trans.flush()

@Swixx already make pull request to  thrift_sasl
