### ISSUE TITLE
conda.exceptions.ResolvePackageNotFound: thrift-sasl

### ISSUE THREAD

**Issue by blacktea-latte** [devinstevenson/pure-transport#3]
Hi there,

I'm trying to install pure-transport using conda's skeleton/build but the above issue occured. It seemed to be a naming issue - this package, as you mentioned in the dependencies list, is named thrift_sasl (note the underscore vs. hyphen) in my current conda environment. 

I understand that pure-transport is supposed to be installed using pip, but is there anything you can do to make this work? Thank you!

**Comment by devinstevenson** [comment]
fixed in 0.1.4 and published to PyPI
